spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    security.protocol: SSL
    ssl:
      trust-store-location: ${KAFKA_SSL_TRUSTSTORE_LOCATION}
      trust-store-password: ${KAFKA_SSL_TRUSTSTORE_PASSWORD}
      key-store-location: ${KAFKA_SSL_KEYSTORE_LOCATION}
      key-store-password: ${KAFKA_SSL_KEYSTORE_PASSWORD}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener.ack-mode: manual
    consumer:
      group_id: ${KAFKA_CONSUMER_GROUP_ID}
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
#      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY}
      topic:
        producer:
          new-items:
            smartphones: ${KAFKA_NEW_ITEMS_SMARTPHONES_TOPIC}
            games: ${KAFKA_NEW_ITEMS_GAMES_TOPIC}
        consumer:
          new-items:
            smartphones: ${KAFKA_NEW_ITEMS_SMARTPHONES_TOPIC}
            games: ${KAFKA_NEW_ITEMS_SMARTPHONES_TOPIC}

parsing:
  cron: ${PARSING_CRONE}
  smartphones:
    citilink:
      base-url: ${CITILINK_BASE_URL}
  games:
    rawg:
      base-url: ${RAWG_BASE_URL}
      api-key: ${RAWG_API_KEY}

logging.level:
  ROOT: debug